print("Problem1")
x = input("You must write something:").strip()
z = x.split(" ")
print(max(z, key=len))
print("Problem2")
q = input("Write something with semicolons:").strip()
w = q.split(";")
print(max(w, key=len))
print('Problem3')
q = input("Write someting so I can find the minimum word:").strip()
a = (input("Write the symbol which will be your divider:"))
w = q.split(a)
print(min(w, key=len))
print("Problem#4")
_some_string = input("Please write some sentence")
f = input("Please write word that you want to find:")
print(_some_string.find(f))
print("Problem#5")
j = input("Please write any sentence:")
h = j.split(" ")
print(len(h))
