# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('avatar', models.ImageField(blank=True, height_field=400, null=True, upload_to=None, width_field=400)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
