# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160402_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=0, unique=True),
        ),
    ]
