# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='password',
        ),
    ]
