# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(default=1, related_name='_post_category_+', to='posts.Post'),
        ),
    ]
