# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160324_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='events',
            field=models.TextField(blank=True, default=0, verbose_name='nsaervgsf'),
        ),
        migrations.AddField(
            model_name='category',
            name='news',
            field=models.TextField(blank=True, default=0, verbose_name='news'),
        ),
        migrations.AddField(
            model_name='category',
            name='other',
            field=models.TextField(blank=True, default=0, verbose_name='ns'),
        ),
        migrations.AddField(
            model_name='category',
            name='useful',
            field=models.TextField(blank=True, default=0, verbose_name='nes'),
        ),
    ]
